<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="index.php">Accueil</a></li>
                <li><a href="index.php?page=contact">Contact</a></li>
                <li><a href="index.php?page=products">Products</a></li>
                <li><a href="index.php?page=account">Account</a></li>
                <li><a href="index.php?page=basket">Basket (
                    <?php if(isset($_SESSION['basket'])) :?>
                        <?= $_SESSION['basket'] ?>
                    <?php endif; ?>
                    )</a></li>
            </ul>
        </nav>
        <?php if(isset($_SESSION['login'])) :?>
            <h1><?= $_SESSION['email'] ?></h1>
        <?php endif; ?>
    </header>
    <main>
        <?php include $template ?>
        
    </main>
    <footer>Copyright - <?= $this->date ?> </footer>
</body>
</html>