<?php foreach($products as $product): ?>
    <ul>
        <li>
            <div>
                <h2><?= $product->getName() ?></h2>
                <h2><?= $product->getDescription() ?></h2>
                <h2>Stock: <?= $product->getStock() ?></h2>
                <p>Price: <?= $product->getPrice() ?></p>
                <img width=100 height=120 src="public/images/<?=$product->getImg()?>" ></img>
            </div>
            <button><a href="index.php?page=product&id=<?= $product->getId() ?>">Details</a></button>
        </li>
    </ul>
<?php endforeach; ?>